name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  NUGET_XMLDOC_MODE: skip
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  lint:
    name: Lint
    uses: nogic1008/actions/.github/workflows/dotnet-format.yml@v2.0.0

  restore:
    name: Validate NuGet Lock Files
    uses: nogic1008/actions/.github/workflows/nuget-lock-files.yml@v2.0.0
    with:
      update-lock-files: ${{ contains(github.head_ref, 'dependabot') && github.event_name == 'pull_request' }}
      dotnet-version: ${{ vars.DOTNET_SDK_VERSIONS }}
      lock-file-path: '**/packages.lock.json'
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

  test:
    name: Debug Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: ${{ vars.DOTNET_SDK_VERSIONS }}
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test --no-build -p:TestingPlatformCommandLineArguments="--coverage --coverage-output-format cobertura --coverage-output ${{ vars.COVERAGE_REPORT_FILE }}"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5.0.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ runner.os }}
          disable_search: true
          files: ${{ vars.TEST_ASSET_FOLDER }}/net8.0/TestResults/${{ vars.COVERAGE_REPORT_FILE }},${{ vars.TEST_ASSET_FOLDER }}/net9.0/TestResults/${{ vars.COVERAGE_REPORT_FILE }}
